-- GradQuest database schema (Postgres / Supabase).
-- Mirrors the JPA entities in src/main/java/com/project03/model.
-- RLS is enabled on every table with no policies: the Spring Boot backend connects
-- as the postgres role (bypasses RLS), while Supabase's public Data API gets no access.

CREATE TABLE IF NOT EXISTS public.users (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             varchar(255) UNIQUE,
    name              varchar(255),
    avatar_url        varchar(255),
    oauth_provider    varchar(255) NOT NULL DEFAULT 'unknown',
    oauth_provider_id varchar(255) NOT NULL DEFAULT '',
    CONSTRAINT users_provider_identity_uk UNIQUE (oauth_provider, oauth_provider_id)
);

CREATE TABLE IF NOT EXISTS public.schools (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 varchar(255) NOT NULL,
    type                 varchar(255) NOT NULL CHECK (type IN ('PUBLIC', 'PRIVATE')),
    state                varchar(255) NOT NULL,
    city                 varchar(255),
    program_name         varchar(255),
    program_type         varchar(255),
    annual_tuition       numeric(10, 2),
    total_cost           numeric(10, 2),
    application_deadline varchar(255),
    application_fee      numeric(10, 2),
    description          text,
    website_url          varchar(255),
    ranking              integer,
    accreditation        varchar(255),
    enrollment_type      varchar(255) CHECK (enrollment_type IN ('PART_TIME', 'FULL_TIME')),
    modality             varchar(255) CHECK (modality IN ('ONLINE', 'IN_PERSON', 'HYBRID')),
    requirement_type     varchar(255) CHECK (requirement_type IN ('CAPSTONE', 'GRE', 'NEITHER', 'BOTH'))
);

CREATE TABLE IF NOT EXISTS public.student_preferences (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           bigint NOT NULL UNIQUE REFERENCES public.users (id) ON DELETE CASCADE,
    budget            double precision NOT NULL,
    school_year       varchar(255) NOT NULL,
    expected_grad     varchar(255) NOT NULL,
    school_type       varchar(255) NOT NULL CHECK (school_type IN ('PUBLIC', 'PRIVATE', 'BOTH')),
    state             varchar(255) NOT NULL,
    program_type      varchar(255),
    target_country    varchar(255),
    major             varchar(255),
    enrollment_type   varchar(255) CHECK (enrollment_type IN ('PART_TIME', 'FULL_TIME')),
    modality          varchar(255) CHECK (modality IN ('ONLINE', 'IN_PERSON', 'HYBRID')),
    gpa               double precision,
    capstone_required varchar(255) CHECK (capstone_required IN ('CAPSTONE', 'GRE', 'NEITHER', 'BOTH'))
);

CREATE TABLE IF NOT EXISTS public.applications (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    school_id            bigint NOT NULL REFERENCES public.schools (id) ON DELETE CASCADE,
    program_name         varchar(255),
    application_deadline date,
    status               varchar(255) NOT NULL CHECK (status IN ('PENDING', 'SUBMITTED', 'ACCEPTED', 'REJECTED')),
    notes                text,
    submission_date      date,
    decision_date        date
);

CREATE TABLE IF NOT EXISTS public.reminders (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    application_id bigint REFERENCES public.applications (id) ON DELETE CASCADE,
    school_id      bigint REFERENCES public.schools (id) ON DELETE CASCADE,
    reminder_date  date NOT NULL,
    reminder_time  time,
    title          varchar(255) NOT NULL,
    description    text,
    reminder_type  varchar(255) NOT NULL CHECK (reminder_type IN ('DEADLINE', 'FOLLOW_UP', 'PERSONAL_STATEMENT', 'REFERENCES', 'CUSTOM')),
    is_completed   boolean NOT NULL DEFAULT false,
    created_at     timestamp NOT NULL DEFAULT now(),
    updated_at     timestamp
);

CREATE INDEX IF NOT EXISTS reminders_user_id_idx ON public.reminders (user_id);
CREATE INDEX IF NOT EXISTS reminders_school_id_idx ON public.reminders (school_id);
CREATE INDEX IF NOT EXISTS reminders_application_id_idx ON public.reminders (application_id);
CREATE INDEX IF NOT EXISTS applications_user_id_idx ON public.applications (user_id);
CREATE INDEX IF NOT EXISTS applications_school_id_idx ON public.applications (school_id);

ALTER TABLE public.users               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schools             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reminders           ENABLE ROW LEVEL SECURITY;
