-- Sample school data for development.
-- States use two-letter codes to match the intake form; deadlines are ISO dates (YYYY-MM-DD)
-- because ReminderController parses them with LocalDate.parse.
-- Rows whose description starts with 'MOCK DATA:' are invented test programs:
--   DELETE FROM public.schools WHERE description LIKE 'MOCK DATA:%';

INSERT INTO public.schools
    (name, type, state, city, program_name, program_type, annual_tuition, total_cost, application_deadline, application_fee, description, website_url, ranking, accreditation, enrollment_type, modality, requirement_type)
VALUES
('Harvard University','PRIVATE','MA','Cambridge','Master of Science in Computer Science','Computer Science',59320,86926,'2026-11-01',90,'Harvard is the oldest institution of higher education in the U.S., known for its extensive research output, diverse academic programs, and global leadership in many fields.','https://www.harvard.edu/',1,'NECHE','FULL_TIME','IN_PERSON','CAPSTONE'),
('Stanford University','PRIVATE','CA','Stanford','Master of Science in Mathematics','Math',65910,92892,'2026-12-18',90,'Stanford is a private research university in California renowned for its strong programs across engineering, humanities, business, and its high selectivity.','https://www.stanford.edu',2,'WASC','FULL_TIME','IN_PERSON','CAPSTONE'),
('Massachusetts Institute of Technology','PRIVATE','MA','Cambridge','Master of Science in Biology','Biology',50000,80000,'2027-12-01',75,'MIT is a private research university focused on science, technology, engineering, and mathematics, widely ranked among the top universities in the world.','https://www.mit.edu',3,'NECHE','FULL_TIME','IN_PERSON','CAPSTONE'),
('University of Washington','PUBLIC','WA','Seattle','Master of Science in Computer Science','Computer Science',18915,56745,'2026-12-15',90,'Leading public research university in the Pacific Northwest','https://www.washington.edu',16,'NWCCU','FULL_TIME','IN_PERSON','CAPSTONE'),
('University of California Berkeley','PUBLIC','CA','Berkeley','Master of Arts in Mathematics','Math',14226,42678,'2026-12-01',135,'Premier public research university known for academic excellence','https://www.berkeley.edu',3,'WASC','PART_TIME','IN_PERSON','CAPSTONE'),
('Columbia University','PRIVATE','NY','New York','Master of Arts in English','English',63530,127060,'2027-01-10',100,'Ivy League institution in the heart of Manhattan','https://www.columbia.edu',5,'MSCHE','FULL_TIME','HYBRID','CAPSTONE'),
('University of Virginia','PUBLIC','VA','Charlottesville','Master of Arts in Psychology','Psychology',21250,63750,'2026-12-05',75,'Historic public university founded by Thomas Jefferson','https://www.virginia.edu',25,'SACSCOC','FULL_TIME','IN_PERSON','CAPSTONE'),
('Boston University','PRIVATE','MA','Boston','Master of Science in Biology','Biology',58560,117120,'2026-12-15',95,'Large private research university with diverse programs','https://www.bu.edu',43,'NECHE','FULL_TIME','IN_PERSON','CAPSTONE'),
('University of Michigan','PUBLIC','MI','Ann Arbor','Master of Science in Chemistry','Chemistry',26336,52672,'2027-01-05',90,'Top public research university with comprehensive programs','https://www.umich.edu',4,'HLC','PART_TIME','IN_PERSON','CAPSTONE'),
('Carnegie Mellon University','PRIVATE','PA','Pittsburgh','Master of Science in Computer Science','Computer Science',61344,122688,'2026-12-10',75,'World leader in computer science and engineering','https://www.cmu.edu',3,'MSCHE','FULL_TIME','IN_PERSON','CAPSTONE'),
('University of Texas Austin','PUBLIC','TX','Austin','Master of Science in Mathematics','Math',12036,36108,'2026-12-01',90,'Flagship public university with strong research programs','https://www.utexas.edu',8,'SACSCOC','FULL_TIME','HYBRID',NULL),
('Yale University','PRIVATE','CT','New Haven','Master of Arts in English','English',64700,129400,'2027-01-02',100,'Ivy League university with distinguished humanities programs','https://www.yale.edu',4,'NECHE','FULL_TIME','IN_PERSON','CAPSTONE'),
('University of California Los Angeles','PUBLIC','CA','Los Angeles','Master of Arts in Psychology','Psychology',13896,41688,'2026-12-15',140,'Prestigious public research university in Southern California','https://www.ucla.edu',6,'WASC','FULL_TIME','IN_PERSON','CAPSTONE'),
('Johns Hopkins University','PRIVATE','MD','Baltimore','Master of Science in Biology','Biology',62840,125680,'2027-01-15',100,'Leading research university especially strong in sciences','https://www.jhu.edu',7,'MSCHE','PART_TIME','IN_PERSON','CAPSTONE'),
('University of Illinois Urbana-Champaign','PUBLIC','IL','Urbana','Master of Science in Chemistry','Chemistry',19364,58092,'2026-12-15',70,'Top engineering and science public university','https://www.illinois.edu',12,'HLC','FULL_TIME','ONLINE',NULL),
('Georgia Institute of Technology','PUBLIC','GA','Atlanta','Master of Science in Computer Science','Computer Science',13788,41364,'2027-01-01',85,'Premier engineering and technology focused institution','https://www.gatech.edu',10,'SACSCOC','PART_TIME','ONLINE',NULL),
('University of Wisconsin Madison','PUBLIC','WI','Madison','Master of Science in Mathematics','Math',12608,37824,'2027-01-10',75,'Top-tier public research university in the Midwest','https://www.wisc.edu',15,'HLC','FULL_TIME','IN_PERSON','CAPSTONE'),
('Duke University','PRIVATE','NC','Durham','Master of Arts in Psychology','Psychology',63450,126900,'2026-12-20',95,'Elite private research university with strong academics','https://www.duke.edu',9,'SACSCOC','PART_TIME','HYBRID','CAPSTONE'),
('University of Colorado Boulder','PUBLIC','CO','Boulder','Master of Science in Mathematics','Math',16854,50562,'2026-11-30',60,'Research university in the Rocky Mountains','https://www.colorado.edu',32,'HLC','FULL_TIME','IN_PERSON','CAPSTONE'),
('Emory University','PRIVATE','GA','Atlanta','Master of Arts in English','English',59920,119840,'2027-01-08',65,'Private research university with strong liberal arts','https://www.emory.edu',24,'SACSCOC','PART_TIME','HYBRID','CAPSTONE'),
('University of Rochester','PRIVATE','NY','Rochester','Master of Arts in Psychology','Psychology',62140,124280,'2026-12-03',45,'Private research university in upstate New York','https://www.rochester.edu',47,'MSCHE','FULL_TIME','IN_PERSON','CAPSTONE'),
('Case Western Reserve University','PRIVATE','OH','Cleveland','Master of Science in Biology','Biology',56850,113700,'2027-01-12',55,'Private research university with strong STEM programs','https://www.case.edu',53,'HLC','FULL_TIME','IN_PERSON','CAPSTONE'),
('Texas A&M University','PUBLIC','TX','College Station','Master of Science in Chemistry','Chemistry',11450,34350,'2026-12-08',48,'Large public research university with strong engineering','https://www.tamu.edu',39,'SACSCOC','PART_TIME','ONLINE','CAPSTONE'),
('University of California San Diego','PUBLIC','CA','San Diego','Master of Science in Computer Science','Computer Science',15102,45306,'2026-12-12',120,'Top public research university on the Pacific coast','https://www.ucsd.edu',21,'WASC','FULL_TIME','IN_PERSON','CAPSTONE'),
('Indiana University Bloomington','PUBLIC','IN','Bloomington','Master of Arts in English','English',11790,35370,'2026-11-28',42,'Major public research university with strong humanities','https://www.indiana.edu',36,'HLC','FULL_TIME','HYBRID','CAPSTONE'),
('Wake Forest University','PRIVATE','NC','Winston-Salem','Master of Arts in Psychology','Psychology',61140,122280,'2027-01-06',58,'Private university known for undergraduate focus','https://www.wfu.edu',29,'SACSCOC','FULL_TIME','IN_PERSON','CAPSTONE'),
('Tufts University','PRIVATE','MA','Medford','Master of Science in Biology','Biology',67844,135688,'2026-12-28',82,'Private research university near Boston','https://www.tufts.edu',44,'NECHE','PART_TIME','IN_PERSON','CAPSTONE'),
('University of California Irvine','PUBLIC','CA','Irvine','Master of Science in Chemistry','Chemistry',15516,46548,'2027-01-14',118,'Growing public research university in Orange County','https://www.uci.edu',35,'WASC','FULL_TIME','ONLINE','CAPSTONE'),
('University of Delaware','PUBLIC','DE','Newark','Master of Science in Mathematics','Math',17930,53790,'2026-12-06',52,'Public research university with strong science programs','https://www.udel.edu',97,'MSCHE','FULL_TIME','IN_PERSON','CAPSTONE'),
('Lehigh University','PRIVATE','PA','Bethlehem','Master of Science in Computer Science','Computer Science',60490,120980,'2026-12-22',68,'Private research university in eastern Pennsylvania','https://www.lehigh.edu',51,'MSCHE','PART_TIME','HYBRID','CAPSTONE'),
('University of Connecticut','PUBLIC','CT','Storrs','Master of Arts in English','English',18448,55344,'2026-11-25',38,'Flagship public research university in New England','https://www.uconn.edu',58,'NECHE','FULL_TIME','IN_PERSON','CAPSTONE'),
('University of Iowa','PUBLIC','IA','Iowa City','Master of Arts in Psychology','Psychology',11427,34281,'2027-01-18',46,'Major public research university in the Midwest','https://www.uiowa.edu',67,'HLC','FULL_TIME','IN_PERSON','CAPSTONE'),
('San Jose State University','PUBLIC','CA','San Jose','MS Computer Science','Computer Science',18000,36000,'2026-12-01',90,'MOCK DATA: Industry-focused CS master''s in Silicon Valley.','https://www.sjsu.edu',45,'WASC','FULL_TIME','IN_PERSON','NEITHER'),
('UC San Diego','PUBLIC','CA','La Jolla','MS Computer Science','Computer Science',32000,64000,'2026-12-15',135,'MOCK DATA: Research-oriented CS program with thesis option.','https://www.ucsd.edu',12,'WASC','FULL_TIME','IN_PERSON','BOTH'),
('CSU Monterey Bay','PUBLIC','CA','Seaside','MS Applied Mathematics','Math',15000,30000,'2027-02-01',70,'MOCK DATA: Applied math with a capstone project.','https://csumb.edu',80,'WASC','PART_TIME','HYBRID','CAPSTONE'),
('Stanford University','PRIVATE','CA','Stanford','MA English','English',62000,124000,'2026-12-05',125,'MOCK DATA: Literature and writing master''s program.','https://www.stanford.edu',3,'WASC','FULL_TIME','IN_PERSON','GRE'),
('NYU','PRIVATE','NY','New York','MS Computer Science','Computer Science',58000,116000,'2027-01-15',110,'MOCK DATA: CS master''s in Manhattan with flexible tracks.','https://www.nyu.edu',20,'MSCHE','FULL_TIME','IN_PERSON','NEITHER'),
('CUNY Hunter College','PUBLIC','NY','New York','MA English','English',12000,24000,'2027-03-01',75,'MOCK DATA: Affordable English MA with capstone essay.','https://www.hunter.cuny.edu',90,'MSCHE','PART_TIME','HYBRID','CAPSTONE'),
('Columbia University','PRIVATE','NY','New York','MA Mathematics','Math',65000,130000,'2027-01-05',120,'MOCK DATA: Rigorous pure and applied math master''s.','https://www.columbia.edu',8,'MSCHE','FULL_TIME','IN_PERSON','GRE'),
('UT Austin','PUBLIC','TX','Austin','MS Computer Science (Online)','Computer Science',10000,20000,'2027-02-15',65,'MOCK DATA: Low-cost fully online CS master''s.','https://www.utexas.edu',15,'SACSCOC','PART_TIME','ONLINE','NEITHER'),
('Texas A&M University','PUBLIC','TX','College Station','MS Mathematics','Math',20000,40000,'2027-01-10',90,'MOCK DATA: Math master''s with research and teaching assistantships.','https://www.tamu.edu',30,'SACSCOC','FULL_TIME','IN_PERSON','BOTH'),
('Rice University','PRIVATE','TX','Houston','MA English','English',54000,108000,'2026-12-20',85,'MOCK DATA: Small-cohort English program.','https://www.rice.edu',18,'SACSCOC','FULL_TIME','IN_PERSON','GRE'),
('University of Washington','PUBLIC','WA','Seattle','MS Computer Science (Professional)','Computer Science',28000,56000,'2027-01-20',85,'MOCK DATA: Evening professional master''s for working engineers.','https://www.washington.edu',10,'NWCCU','PART_TIME','HYBRID','CAPSTONE'),
('Western Washington University','PUBLIC','WA','Bellingham','MA English','English',14000,28000,'2027-02-28',60,'MOCK DATA: Online-friendly English MA.','https://www.wwu.edu',70,'NWCCU','PART_TIME','ONLINE','NEITHER');
